services:
  api:
    container_name: isebelle-api
    build: ./api

    volumes:
      - ./api:/app:Z
      - ${STORIES_SRC_FOLDER:?}:/stories
      - ${CACHE_FOLDER:-./isebelle-cache}:/static

    environment:
      DB_HOST: db
      DB_PORT: 5432
      PUBLIC_API_BASE: /isebelle/api

      DB_NAME: ${DB_NAME:?}
      DB_USER: ${DB_USER:?}
      DB_PASSWORD: ${DB_PASSWORD:?}
      JUPYTER_TOKEN: ${JUPYTER_PASSWORD:?}
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
      STORIES_SRC_FOLDER: /stories
      CACHE_FOLDER: /static

    depends_on:
      - db

    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf'

  web-ui:
    container_name: isebelle-web-ui
    build: ./web-ui

    volumes:
      - ./web-ui:/app:Z

    environment:
      PUBLIC_API_BASE: /isebelle/api
      COREPACK_ENABLE_AUTO_PIN: 0

  db:
    container_name: isebelle-db
    image: ankane/pgvector
    shm_size: 1g

    volumes:
      - isebelle-db-data:/var/lib/postgresql/data

    environment:
      POSTGRES_DB: ${DB_NAME:?}
      POSTGRES_USER: ${DB_USER:?}
      POSTGRES_PASSWORD: ${DB_PASSWORD:?}

  ollama:
    container_name: isebelle-ollama
    build: ./ollama

    ports: 
      - 11434:11434
    volumes:
      - ./ollama:/root/.ollama

    pull_policy: always
    tty: true
    restart: unless-stopped

  web-proxy:
    &proxy
    profiles:
        - ''
    container_name: isebelle-web-proxy
    image: nginx:alpine
    ports:
      - ${APP_HOST:-127.0.0.1}:${APP_PORT:-8080}:80

    volumes:
      - ./nginx.config:/etc/nginx/conf.d/default.conf
      - ${CACHE_FOLDER:-./isebelle-cache}:/static
      - ./web-ui:/app

    depends_on:
      - api
      - web-ui

    stop_grace_period: 0s

  web-proxy-tls:
    <<: *proxy
    profiles:
      - tls
    ports:
      - ${APP_HOST:-127.0.0.1}:${APP_PORT:-8080}:80
      - ${APP_HOST:-127.0.0.1}:443:443
    volumes:
      - ./nginx.tls.config:/etc/nginx/conf.d/default.conf
      - ${CACHE_FOLDER:-./isebelle-cache}:/static
      - ./web-ui:/app
      - ../ssl:/ssl

volumes:
  isebelle-db-data:
